---
title: "Data Toolbox"
href: toolbox
---

Initially based on [a list by Prof. Bahareh Heravi](https://nitter.net/Bahareh360), with some additions from me. You can find [a list of even more tools on SPJ Toolbox](https://www.journaliststoolbox.org/category/data-visualization-and-online-tools/).

## Collection
- [Web Scraper](https://webscraper.io/) — browser plugin for scraping
- [Outwit Hub](https://www.outwit.com/products/hub/OutWit-Hub-Light-Pro-Expert-Enterprise-editions) — desktop app for scraping
- [Parsehub](https://www.parsehub.com/) — desktop app for scraping
- [Visualping](https://visualping.io/) — monitor website changes
- [Tabula](http://tabula.technology/) — get data from PDFs
- [WebPlotDigitize](https://aps.automeris.io/wpd/) — digitise image charts
- [Map Digitizer](https://mapster.me/map-digitizer/) — digitise image maps
- [IFTTT](https://ifttt.com/) — automate tasks
- [NodeXL](http://www.smrfoundation.org/nodexl/) — network analysis
- [Media Cloud](https://www.mediacloud.org/) — media analysis
- [R](https://rvest.tidyverse.org/) / [rvest](https://rvest.tidyverse.org/) — programming language
- [Python](https://www.crummy.com/software/BeautifulSoup/) / [beautifulsoup](https://www.crummy.com/software/BeautifulSoup/) — programming language
- [Selenium](https://www.selenium.dev/) — browser automation
- [curl converter](https://curlconverter.com/) — convert curl commands to Python, JS, R, etc.
- [SelectorGadget](https://selectorgadget.com/) — CSS selector helper
- [data.page](https://data.page/json/csv) — JSON to CSV converter
- [SVG crowbar](https://nytimes.github.io/svg-crowbar/) — lift SVG off of webpages


## FOIA
- [FOIA Wiki](https://foia.wiki/wiki/Main_Page) — FOIA resources (US-focused)
- [Data Liberation Project](https://www.data-liberation-project.org/) — released government datasets
- [WhatDoTheyKnow](https://www.whatdotheyknow.com/) — FOIA tool and catalogue


## Wrangling
- [Microsoft Excel](https://www.microsoft.com/en-gb/microsoft-365/excel) — desktop spreadsheets app
- [Google Sheets](https://www.google.com/sheets/about/) — free spreadsheets web app
- [OpenRefine](http://openrefine.org/) — data cleaning and transformation ([R implementation](https://github.com/ChrisMuir/refinr))
- [Parserator](https://parserator.datamade.us/) — parse addresses and other unstructured text
- [Geocodio](https://www.geocod.io/) — geocode 🇺🇸🇨🇦 addresses


## Analysis
- [Microsoft Excel](https://www.microsoft.com/en-gb/microsoft-365/excel) — desktop spreadsheets app
- [Google Sheets](https://www.google.com/sheets/about/) — free spreadsheets web app
- [R](https://rvest.tidyverse.org/) / [rvest](https://rvest.tidyverse.org/) — programming language
- [Python](https://www.crummy.com/software/BeautifulSoup/) / [beautifulsoup](https://www.crummy.com/software/BeautifulSoup/) — programming language
- [SPSS](https://www.ibm.com/spss) — statistical analysis software
- [PSPP](https://www.gnu.org/software/pspp/) — statistical analysis software
- [Tableau](https://www.tableau.com/) (paid) — data analysis and visualisation tool
- [QGIS](https://qgis.org/en/site/) — desktop mapping software
- [CARTO](https://carto.com/) — web mapping software


## Visualisation
- [Datawrapper](http://datawrapper.de/) — web dataviz tool
- [Flourish](http://flourish.studio/) — web interactive/dataviz tool
- [RAW Graphs](https://www.rawgraphs.io/) — static chart maker
- [Infogram](https://infogram.com/) — infographic creator
- [Datamatic.io](http://datamatic.io/) — web dataviz tool
- [Highcharts](https://www.highcharts.com/) — chart library for developers
- [Plotly](https://plot.ly/) — chart library for developers
- [D3.js](https://d3js.org/) — library for advanced dataviz
- [Mapbox](https://www.mapbox.com/) — map maker
- [Mapshaper](https://mapshaper.org/) — editor for map data
- [geojson.io](https://geojson.io/) — editor for map data
- [Gephi](https://gephi.org/) — network visualisations
- [R](https://www.r-project.org/) / [ggplot2](http://ggplot2.org/) — programming language
