project:
  type: website
  output-dir: docs
  post-render: 
    - _observable/render_scripts/generate_config.py
    - _observable/render_scripts/build.bat

website:
  title: "Data Journalism Wiki"
  favicon: favicon.png
  navbar:
    left:
      - text: Home
        icon: "house"
        href: index.qmd
      - text: "Data Sources"
        icon: "table"
        menu:
          - text: "Data Sources"
            icon: "table"
            href: sources/index.qmd
          - text: "Academic Sources"
            icon: "mortarboard"
            href: sources/academic.qmd
          - text: "Data Calendar"
            icon: "calendar-week"
            href: sources/data-calendar.qmd
      - text: Toolbox
        icon: "tools"
        href: toolbox/index.qmd
      - text: Awards
        icon: "trophy"
        href: awards/index.qmd
      - text: LLM comparison
        icon: "robot"
        href: llm.html
    tools:
      - icon: c-circle
        href: https://nicu.md/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nicucalcea/ddj-wiki
          - text: Report an Issue
            url:  https://github.com/nicucalcea/ddj-wiki/issues
  repo-url: https://github.com/nicucalcea/ddj-wiki
  repo-actions: [edit, issue]
  site-url: https://ddj.nicu.md/
  page-footer: "Copyright 2023, <a href='https://nicu.md/'>Nicu Calcea</a>"

format:
  html:
    theme: darkly
    toc: true

editor: source

resources:
  - CNAME