project:
  type: website
  output-dir: docs

website:
  title: "Data Journalism Wiki"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - intro/index.qmd
      - sources/index.qmd
      # - city/index.qmd
    tools:
      - icon: person-circle
        href: https://nicu.md/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nicucalcea/ddj-wiki
          - text: Report an Issue
            url:  https://github.com/nicucalcea/ddj-wiki/issues
  repo-url: https://github.com/nicucalcea/ddj-wiki
  repo-actions: [edit, issue]
  site-url: http://nicu.md/ddj-wiki/
  page-footer: "Copyright 2023, <a href='https://nicu.md/'>Nicu Calcea</a>"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: source