project:
  type: website

website:
  title: "Investigative Data Journalism Training"
  favicon: favicon.png
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:resources
      - sidebar:lessons
      - text: About
        href: https://nicu.md
      - href: "mailto:training@nicu.md?subject=Data Training"
        text: Contact
    tools:
      - icon: envelope
        href: mailto:training@nicu.md?subject=Data Training
  sidebar:
    - id: resources
      title: "Resources"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Data Sources
          contents:
            - sources/index.qmd
            - sources/academic.qmd
            - sources/calendar.qmd
        - section: Toolbox
          contents:
            - toolbox/index.qmd
        - section: Events
          contents:
            - awards/index.qmd
    - id: lessons
      title: "Lessons"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Data Journalism
          contents:
            - ddj/index.qmd
            # - sources/index.qmd
        - section: Generative AI
          contents:
            - ai/index.qmd
            - ai/google-sheets.qmd
            - ai/python-classification-agent.ipynb
  page-footer: "Copyright 2025, Nicu Calcea • Made with 💜 in London"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light:
        - flatly
        - brand
      dark:
        - darkly
        - brand
    css: styles/style.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true

brand:
  light: styles/brand-light.yml
  dark: styles/brand-dark.yml