project:
  type: website
  output-dir: docs
  post-render: 
    - _observable/render_scripts/generate_config.py
    - _observable/render_scripts/build.bat

website:
  title: "Data Journalism Wiki"
  favicon: favicon.png
  page-navigation: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: "Data Sources"
        # icon: "table"
        contents:
          - text: "Data Sources"
            icon: "table"
            href: sources/index.qmd
          - text: "Academic Sources"
            icon: "mortarboard"
            href: sources/academic.qmd
          - text: "Data Calendar"
            icon: "calendar-week"
            href: sources/calendar.qmd
      - section: "AI"
        # icon: "robot"
        contents:
          - text: "AI for journalists"
            icon: "robot"
            href: ai/index.qmd
          - text: "AI in Google Sheets"
            icon: "file-earmark-spreadsheet"
            href: ai/google-sheets.qmd
          - text: "LLM comparison"
            icon: "currency-dollar"
            href: ai/llm-comparison.html
      - text: Toolbox
        icon: "tools"
        href: toolbox/index.qmd
      - text: Awards
        icon: "trophy"
        href: awards/index.qmd
  repo-url: https://github.com/nicucalcea/ddj-wiki
  repo-actions: [edit, issue]
  site-url: https://ddj.nicu.md/
  page-footer: "<a href='https://nicu.md/' target='_blank'>Copyright 2024, Nicu Calcea</a>."

format:
  html:
    theme:
      - cyborg
      - style.scss
    toc: true
    code-overflow: wrap

editor: source

resources:
  - CNAME