---
title: "Introduction to Data Journalism"
subtitle: "What is it and why do we need it?"
---

Data Journalism goes by different names. It can be called data-driven journalism, computer-assisted reporting or CAR (in the US), precision journalism. Its history is even older than that though: the [first edition of the Manchester Guardian](https://www.theguardian.com/news/datablog/2011/sep/26/data-journalism-guardian){target="_blank"} had a data journalism article. So don't focus too much on what you call it.

> In its most simple definition, data journalism is the practice of using numbers and trends to tell a story. - Betsy Ladyzhets

Data journalism does not mean you have to limit yourself to data: we do everything else other reporters do, including developing contacts, interviewing sources, sending FOIs, doing field investigations, checking facts, writing, editing, multimedia (when relevant), etc. At the NS, data journalists are usually in charge of their stories from start to end, we're not just a graphics desk.

Some people even have their own beats. I have data journalist colleagues who focus on particular beats, like politics, the environment, business, even fine wines (World of Fine Wines).

Data can be hard and complex, you'll always want to reach out to experts who can explain things for you. Energy consumption map as an example.

> Data journalism \[is\] finding -- in data -- stories that are of interest to the public and presenting them in the most appropriate manner for public use and reuse. --- Bahareh Heravi

```{=html}
<div class="flourish-embed flourish-timeline" data-src="visualisation/14307302?1293534"><script src="https://public.flourish.studio/resources/embed.js"></script></div>
```

Despite newsrooms struggling and reducing in size, data journalism teams are growing.

## Job trends in data journalism

Since the pandemic, nearly every newsrooms has prioritised data journalism and has been massively hiring for data journalism positions. Data teams like the one at the FT and the BBC are now so big they need to be split into two or more teams.

New(-ish) platforms like **Datawrapper** and **Flourish** allow journalists to create and visualise data stories easier and without much technical expertise.

However, the increased supply of data journalists from courses like this means there are higher entry requirements (**R**, **Python**, **SQL**). There are R, Python and SQL courses on Datacamp, which you have access to for free.

## Why do we need data journalism?

#### Tell richer stories

An increasing amount of human activity is recorded with data. This means there is a data angle for almost any subject.

#### Be more efficient

We tell some stories every year, month or day. We can greatly simplify or even automate those stories, giving us more time to focus on in-depth reporting.

#### Be more accurate

Though not without data quality issues and ethical considerations, accuracy is central to data journalism.

#### Unique angles

There are now stories where a data angle is the only or main angle. By using data, journalists can create news instead of covering them.

#### Personalise news

Make readers invested in a story by personalising it to their postcode, age or socio-economic status.

#### New audiences

Data journalism is exciting (I hope). The pandemic has shown that readers like clear, beautiful data stories and will reward publishers with their clicks.
