---
title: "Intro to Data Journalism"
subtitle: "City, University of London<br><a href='https://ddj.nicu.md/city/'>https://ddj.nicu.md/city/</a>"
format:
  revealjs:
    theme: [night, css/custom.scss]
    multiplex: true
    chalkboard: 
      buttons: false
href: city
---

# [👋]{.wave} Welcome to [Introduction to Data Journalism]{style="color:#F44336;"}

```{=html}
<style>
  .wave {
  animation-name: wave-animation;  /* Refers to the name of your @keyframes element below */
  animation-duration: 2.5s;        /* Change to speed up or slow down */
  animation-iteration-count: infinite;  /* Never stop waving :) */
  transform-origin: 70% 70%;       /* Pivot around the bottom-left palm */
  display: inline-block;
}

@keyframes wave-animation {
    0% { transform: rotate( 0.0deg) }
   10% { transform: rotate(14.0deg) }  /* The following five values can be played with to make the waving more or less extreme */
   20% { transform: rotate(-8.0deg) }
   30% { transform: rotate(14.0deg) }
   40% { transform: rotate(-4.0deg) }
   50% { transform: rotate(10.0deg) }
   60% { transform: rotate( 0.0deg) }  /* Reset for the last half to pause */
  100% { transform: rotate( 0.0deg) }
}
</style>
```
## Who am I?

My name is Nicu Calcea.

I'm a data journalist and City University alumnus, originally from Moldova, currently based in London.

I work as a data journalist at *BBC News*, previously Data Projects Editor at the *New Statesman*.

::: notes
I graduated 4 years ago and did this module 5 years ago.

You can email me with any questions about these slides, examples I've given, assignments, etc.

I do have a full time job, so for any administrative or urgent queries, please contact Glyn.
:::

::: footer
My personal website: [nicu.md](https://nicu.md/)
:::

## Who are you?

-   What's your name?
-   What course are you in?
-   Do you have any experience in data journalism?
-   Why did you choose this module?

::: notes
Sorry if I mispronounce all of your names and also sorry if I don't remember everyone's name. I will do my best.

I understand we are at different levels of experience. You have access to datacamp which will let you move ahead if you want to get a bit more from this module.
:::

## What is Data Journalism?

> In its most simple definition, data journalism is the practice of using numbers and trends to tell a story. --- Betsy Ladyzhets

::: notes
Some people call it data-driven journalism, computer-assisted reporting or CAR (in the US), precision journalism. It's history is even older than that though: the first edition of the Manchester Guardian had a data journalism article. So don't focus too much on what you call it.
:::

> Data journalism \[is\] finding -- in data -- stories that are of interest to the public and presenting them in the most appropriate manner for public use and reuse. --- Bahareh Heravi

::: notes
Data journalism does not mean you have to limit yourself to data: we do everything else other reporters do, including developing contacts, interviewing sources, sending FOIs, doing field investigations, checking facts, writing, editing, multimedia (when relevant), etc. At the NS, data journalists are usually in charge of their stories from start to end, we're not just a graphics desk.

Some people even have their own beats. I have data journalist colleagues who focus on particular beats, like politics, the environment, business, even fine wines (World of Fine Wines).

Data can be hard and complex, you'll always want to reach out to experts who can explain things for you. Energy consumption map as an example.
:::

## History of Data Journalism

```{=html}
<div class="flourish-embed flourish-timeline" data-src="visualisation/14307302?1293534"><script src="https://public.flourish.studio/resources/embed.js"></script></div>
```
## Job trends

::: columns
::: {.column width="33.33%"}
Since the pandemic, nearly every newsrooms has prioritised data journalism and has been massively hiring for data journalism positions.
:::

::: {.column width="33.33%"}
New(-ish) platforms like Datawrapper and Flourish allow journalists to create and visualise data stories easier and without much technical expertise.
:::

::: {.column width="33.33%"}
However, the increased supply of data journalists from courses like this means there are higher entry requirements (R, Python, SQL).
:::
:::

::: notes
Data teams like the one at the FT and the BBC are now so big they need to be split into two teams.

There are R, Python and SQL courses on Datacamp, which you have access to for free.
:::

<!-- ## {background-iframe="https://www.nytimes.com/interactive/2022/10/04/climate/south-asia-monsoon-climate-change.html?unlocked_article_code=BXzpmSDLKRmxex3aAJ0NuQP4B9ZaOm8vB09LF5jYNC4Dn82EyfEyNgTQB9JpT2OSxMQNxfgkr5rXOex7CcVI291C6r6dECugn6AQn-t_Q-AZpkmodsbd1jMUxHaq-4idE2cOH_E3W8g2XzUqeN2JPp4mzkfoQwSUrV-MNG3Ppox4Gan-eR0KJsUBFYGixnoeM7BYIhDGfezZ5lWGI1MXdst1NgsJJy7RuxQVXHzRkucWXA57hlz1_6RbQ_S-QCp7DBS9VpNYlNnMqH1s4wxcsblMSKPueG9T4nObZpslM_m_r6qdRQ2R8R4MhwkS3eNSghh0jqS_LBzmJvA40_dpEYN5xtxGge9o0N-w_HuYFnEXZrjJJdRFCxhRkA&smid=share-url" background-interactive=true} -->

## Code example

``` scala
=LET(hello,"Hello World, ",hello & Sheet1!$A2 & "!")
```
